global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'service-1'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['service-1-moderation:8081']

  - job_name: 'service-2'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['service-2-enrichment:8082']
